spring.application.name=account

server.port=8000
server.address=0.0.0.0
server.error.include-stacktrace=never

spring.datasource.url=jdbc:h2:file:./data/testdb
spring.jpa.hibernate.ddl-auto=update
client.api.url=http://localhost:8001